### ISSUE TITLE
Should not require new relic or toadhopper

### ISSUE THREAD

**Issue by JustinAiken** [adhearsion/adhearsion-reporter#7]
If you're just wanting airbrake notifications, needing to install the new relic agent's a bummer... and vica-versa.

**Comment by bklang** [comment]
Closing for lack of ideas on how to do this.

**Comment by benlangfeld** [comment]
We know how to do this, simply specifying that users must install these themselves and removing them as dependencies of this gem.

The problem is no-one cares very much about this as evidenced by an issue cold for two years. I'd let it die on that basis.

**Comment by JustinAiken** [comment]
> We know how to do this, simply specifying that users must install these themselves and removing them as dependencies of this gem.

Yeah, pretty much: 
```ruby
begin
  require 'toadhopper` 
  ...toadhopper stuff..
rescue LoadError
end
```

> The problem is no-one cares very much about this as evidenced by an issue cold for two years. I'd let it die on that basis.

Yep, okay w/ me!
